services:
  db_test:
    image: postgres:14-alpine
    restart: always
    env_file: .env.mastodon-test
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: mastodon
      POSTGRES_DB: mastodon
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    networks: [internal]

  redis_test:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data_test:/data
    networks: [internal]

  search:
    build: ./search
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    volumes:
      - search_data:/usr/share/elasticsearch/data
    networks: [internal]

  web_test:
    build: .
    restart: always
    env_file: .env.mastodon-test
    command: bundle exec puma -C config/puma.rb
    user: '991:991'
    environment:
      PORT: '3001'
    depends_on: [db_test, redis_test, search]
    networks: [internal, external]
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -q --spider --proxy=off localhost:3001/health || exit 1',
        ]

  streaming_test:
    build:
      context: .
      dockerfile: ./streaming/Dockerfile
    restart: always
    env_file: .env.mastodon-test
    command: node ./streaming/index.js
    environment:
      PORT: '4001'
      STREAMING_PORT: '4001'
    depends_on: [db_test, redis_test]
    networks: [internal, external]

  sidekiq_test:
    build: .
    restart: always
    env_file: .env.mastodon-test
    command: bundle exec sidekiq
    user: '991:991'
    depends_on: [db_test, redis_test, search]
    networks: [internal, external]
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 8' || false"]

  bot_test:
    build: /home/xetead/xetead-bot
    restart: always
    env_file: .env.mastodon-test
    environment:
      MASTODON_API_BASE_URL: https://test.xetead.quest
      TZ: Asia/Seoul
    command: ["uv", "run", "--frozen", "--no-dev", "python", "-m", "bot.main"]
    depends_on: [web_test]
    networks: [internal, external]

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on: [web_test]
    networks: [external]

volumes:
  postgres_data_test:
  redis_data_test:
  search_data:

networks:
  internal:
    internal: true # 외부 인터넷 차단
  external:
